version: '3'
services:
    overview:
        build: 
            context: .
            dockerfile: Dockerfile
        image: earthdata-pub-overview
        environment: 
            API_ROOT: "http://localhost:8080"
            DASHBOARD_ROOT: "http://localhost:3000"
            OVERVIEW_ROOT: "http://localhost:8082"
        ports:
            - "8082:8080"
        volumes:
            - ./:/app
        tty: true
